# Generated by Django 5.2 on 2025-05-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['price', 'name']},
        ),
    ]
