# Generated by Django 5.2 on 2025-05-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_name_user_gmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gmail',
            field=models.CharField(default='default_gmail@example.com', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
